# Generated by Django 4.0.4 on 2022-08-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_alter_product_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emaiil',
            new_name='email',
        ),
    ]
