# Generated by Django 4.0.4 on 2022-08-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_2',
        ),
    ]
