# Generated by Django 4.0.4 on 2022-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amonut',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
