# Generated by Django 4.0.4 on 2022-08-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_amonut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amonut',
            new_name='amount',
        ),
    ]
